// Code generated by WrapGen. DO NOT EDIT.
package emptyinterface

import (

	"go.uber.org/mock/gomock"
)

// MockEmptyInterfaceUntyped is a mock of EmptyInterfaceUntyped interface.
type MockEmptyInterfaceUntyped struct {
	ctrl     *gomock.Controller
	recorder *MockEmptyInterfaceUntypedMockRecorder
}

// MockEmptyInterfaceUntypedMockRecorder is the mock recorder for MockEmptyInterfaceUntyped.
type MockEmptyInterfaceUntypedMockRecorder struct {
	mock *MockEmptyInterfaceUntyped
}

// NewMockEmptyInterfaceUntyped creates a new mock instance.
func NewMockEmptyInterfaceUntyped(ctrl *gomock.Controller) *MockEmptyInterfaceUntyped {
	mock := &MockEmptyInterfaceUntyped{ctrl: ctrl}
	mock.recorder = &MockEmptyInterfaceUntypedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmptyInterfaceUntyped) EXPECT() *MockEmptyInterfaceUntypedMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockEmptyInterfaceUntyped) ISGOMOCK() struct{} {
	return struct{}{}
}
