// Code generated by WrapGen. DO NOT EDIT.
package constArrayLength

import (
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockI is a mock of I interface.
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
}

// MockIMockRecorder is the mock recorder for MockI.
type MockIMockRecorder struct {
	mock *MockI
}

// NewMockI creates a new mock instance.
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockI) ISGOMOCK() struct{} {
	return struct{}{}
}

// Bar mocks base method.
func (m *MockI) Bar() [2]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bar")
	ret0, _ := ret[0].([2]int)
	return ret0
}

// Bar indicates an expected call of Bar.
func (mr *MockIMockRecorder) Bar() *IBarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockI)(nil).Bar))
	return &IBarCall{Call: call}
}

// IBarCall wrap *gomock.Call
type IBarCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *IBarCall) Return(arg0 [2]int) *IBarCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *IBarCall) Do(f func() [2]int) *IBarCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *IBarCall) DoAndReturn(f func() [2]int) *IBarCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Baz mocks base method.
func (m *MockI) Baz() [127]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Baz")
	ret0, _ := ret[0].([127]int)
	return ret0
}

// Baz indicates an expected call of Baz.
func (mr *MockIMockRecorder) Baz() *IBazCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Baz", reflect.TypeOf((*MockI)(nil).Baz))
	return &IBazCall{Call: call}
}

// IBazCall wrap *gomock.Call
type IBazCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *IBazCall) Return(arg0 [127]int) *IBazCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *IBazCall) Do(f func() [127]int) *IBazCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *IBazCall) DoAndReturn(f func() [127]int) *IBazCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Corge mocks base method.
func (m *MockI) Corge() [7]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Corge")
	ret0, _ := ret[0].([7]int)
	return ret0
}

// Corge indicates an expected call of Corge.
func (mr *MockIMockRecorder) Corge() *ICorgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Corge", reflect.TypeOf((*MockI)(nil).Corge))
	return &ICorgeCall{Call: call}
}

// ICorgeCall wrap *gomock.Call
type ICorgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ICorgeCall) Return(arg0 [7]int) *ICorgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ICorgeCall) Do(f func() [7]int) *ICorgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ICorgeCall) DoAndReturn(f func() [7]int) *ICorgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Foo mocks base method.
func (m *MockI) Foo() [2]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo")
	ret0, _ := ret[0].([2]int)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MockIMockRecorder) Foo() *IFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockI)(nil).Foo))
	return &IFooCall{Call: call}
}

// IFooCall wrap *gomock.Call
type IFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *IFooCall) Return(arg0 [2]int) *IFooCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *IFooCall) Do(f func() [2]int) *IFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *IFooCall) DoAndReturn(f func() [2]int) *IFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Quux mocks base method.
func (m *MockI) Quux() [3]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quux")
	ret0, _ := ret[0].([3]int)
	return ret0
}

// Quux indicates an expected call of Quux.
func (mr *MockIMockRecorder) Quux() *IQuuxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quux", reflect.TypeOf((*MockI)(nil).Quux))
	return &IQuuxCall{Call: call}
}

// IQuuxCall wrap *gomock.Call
type IQuuxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *IQuuxCall) Return(arg0 [3]int) *IQuuxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *IQuuxCall) Do(f func() [3]int) *IQuuxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *IQuuxCall) DoAndReturn(f func() [3]int) *IQuuxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Qux mocks base method.
func (m *MockI) Qux() [3]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Qux")
	ret0, _ := ret[0].([3]int)
	return ret0
}

// Qux indicates an expected call of Qux.
func (mr *MockIMockRecorder) Qux() *IQuxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Qux", reflect.TypeOf((*MockI)(nil).Qux))
	return &IQuxCall{Call: call}
}

// IQuxCall wrap *gomock.Call
type IQuxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *IQuxCall) Return(arg0 [3]int) *IQuxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *IQuxCall) Do(f func() [3]int) *IQuxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *IQuxCall) DoAndReturn(f func() [3]int) *IQuxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
